[global]
# Streamlit configuration for CEAPSI PCF System
developmentMode = false
showWarningOnDirectExecution = false

[server]
# Server settings
port = 8501
address = "localhost"
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[browser]
# Browser settings
serverAddress = "localhost"
gatherUsageStats = false
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Client settings
caching = true
displayEnabled = true
showErrorDetails = false